services:
  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis-data:/data
    restart: always

  bot:
    image: ghcr.io/codemachinee/for_opt_sales:latest
    depends_on:
      - redis
    volumes:
      - ./configs/passwords.py:/app/configs/passwords.py
      - ./configs/pidor-of-the-day-5880592e7067.json:/app/configs/pidor-of-the-day-5880592e7067.json
      - ./loggs.log:/app/loggs.log
    restart: always

volumes:
  redis-data: